version: '3.8'

services:
  stream-api:
    build: .
    container_name: yukki_stream_api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
